version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && gunicorn myproject.wsgi:application -c gunicorn_config.py"
    volumes:
      - .:/app
    ports:
      - "8000:8000"